### ISSUE TITLE
Title bar buttons are not consistent between Qt and GTK

### ISSUE THREAD

**Issue by matty-r** [paulmcauley/classikstyles#3]
Qt app - even spacing between buttons, highlight fills titlebar.

![image](https://user-images.githubusercontent.com/9965448/126034745-ba9958ed-b9fd-4fa2-80d2-058aeb8c6af9.png)

GTK app - much smaller highlight area, spacing much closer together.

![image](https://user-images.githubusercontent.com/9965448/126034764-e8a95f32-7202-4c88-8e5a-8dd954a60424.png)

**Comment by paulmcauley** [comment]
The window decorations for GTK client-side-decorated apps are auto-generated from the Qt ones by a KDE module called kde-gtk-config. This currently generates the window decorations too small: see https://bugs.kde.org/show_bug.cgi?id=436559

Short of manually creating GTK themes, it is better to see if this can be fixed in kde-gtk-config itself.

**Comment by matty-r** [comment]
Closing as it appears to be an upstream bug.
